### ISSUE TITLE
node-minimal template contains live endpoint, instead of localhost

### ISSUE THREAD

**Issue by kbrandwijk** [graphql-cli/graphql-boilerplate#28]
https://github.com/graphql-cli/graphql-boilerplate/blob/877107a3e2a0d0ee32eae2d423f4507a83fecc40/node-minimal/src/index.js#L39-L40

Compared to:

https://github.com/graphql-cli/graphql-boilerplate/blob/ce4b8cb5bd5fe8e5bab513c1037cc7b0b555ce06/typescript-minimal/src/index.ts#L40-L41

Also, isn't the default port 60000, instead of 60001?

**Comment by schickling** [comment]
Fixed.
